export default {
  id: "project-1",
  title: "Unlocking Insights in Healthcare",
  image: "/images/healthcare.png",
  description: "Engineered a healthcare decision-making by building a predictive analytics system that achieved 97% accuracy in patient risk assessment and uncovered $20,000+ cost-saving opportunities through advanced clustering and ML modeling. Transformed raw patient data into an interactive dashboard for real-time monitoring of critical healthcare metrics.",
  technologies: ["SQL", "Python", "Data Analysis", "Data Science"],
  date: "2024-02-01",
  content: `
<p>In the rapidly evolving landscape of healthcare, leveraging data to drive informed decisions is no longer a luxury but a necessity. My latest project delves deep into the realm of healthcare analytics, harnessing the power of SQL databases and Python to uncover actionable insights.</p>
<p>This endeavor encompasses meticulous data preparation, patient segmentation through clustering algorithms, robust predictive modeling to forecast hospitalization charges and assess patient risk scores, geospatial analysis to visualize healthcare metrics across regions, and the development of an interactive dashboard for real-time monitoring. Here&rsquo;s a comprehensive overview of the journey and the methodologies employed.</p>
<p>&nbsp; &nbsp; 1. Data Architecture: laying the foundation<br />&nbsp; &nbsp; 2. Data Preparation: cleaning and structuring SQL integration<br />&nbsp; &nbsp; 3. Patient Segmentation: unveiling clusters<br />&nbsp; &nbsp; 4. Predictive Modeling: forecasting charges and assessing risks<br />&nbsp; &nbsp; 5. Geospatial Analysis: mapping metrics across states<br />&nbsp; &nbsp; 6. Cost Analysis: unveiling financial insights<br />&nbsp; &nbsp; 7. Chronic Disease Management: predicting complications<br />&nbsp; &nbsp; 8. Dashboard development: real-time monitoring with Streamlit<br />&nbsp; &nbsp; 9. Scripts: structuring and querying the data<br />&nbsp; &nbsp; 10. Conclusion</p>
<p><strong>1.&nbsp;Data Architecture: laying the foundation</strong></p>
<p>At the heart of any data-driven project lies a well-structured database. Our healthcare dataset is organized within the&nbsp;<code>healthcare_data</code>&nbsp;schema, comprising three pivotal tables:<br /><br />&nbsp; &nbsp; - hospitalization_details: Customer_ID, date, children, charges, Hospital_tier, City_tier, State_ID<br />&nbsp; &nbsp; - medical_examinations: Customer_ID, HBA1C, Heart_Issues, Any_Transplants, Cancer_History<br />&nbsp; &nbsp; - names: Customer_ID, name</p>
<p><strong>2.&nbsp;Data Preparation: cleaning and structuring SQL integration</strong></p>
<p>Before diving into any analysis, it's imperative to ensure the data's integrity and consistency. The <em>preparedataforSQL.py</em> (you can find it on the linked GitHub at the bottom of the article) script is meticulously crafted to cleanse and preprocess the raw data, making it SQL-ready. Here's a breakdown of its functionalities:</p>
<p>&nbsp; &nbsp; - Processing hospitalization_details.csv: entries with invalid or missing dates are removed, then converts textual month representations (January, February) to numerical values, and restructures the date into a standarized time, following a mm/dd/yyyy format. 'ID' prefix is striped from Customer_ID and we ensure it's an integer. Numerical values are also striped from Hospital_tier and City_tier.<br />&nbsp; &nbsp; - Processing Medical_Examinatios.csv: ID normalization once again, transforms textual description of major surgeries into numerical counts.<br />&nbsp; &nbsp; - Processing Names.xlsx: we ensure consistency across datasets here.</p>
<p>This complete cleaning ensures that the data fed into our analytical model is both accurate and reliable.</p>
<p><strong>3. Patient Segmentation: unveiling clusters</strong></p>
<p>Understanding patient segments is crucial for personalized healthcare strategies, and the <em>patientsegmentation.py&nbsp;</em>script employs k-means clustering algorithm to identify distinct patient groups based on various health metrics and demographic factors.</p>
<p>How so? First we have to connect to the healthcare_data, during this project I made use of MySQL database. Then features are selected: age, children, charges, hospital_tier, city_tier, BMI, HBA1C, heart_issues, any_transplants, cancer_history, numberofmajorsurgeries and smoker.</p>
<p>The data is standarized and features are scaled using StandardScaler to ensure uniformity across all of them. And for optimal cluster determination, we employ the Elbow Method (<em>helps find the optimal number of clusters (k) in k-means clustering by plotting the sum of squared distances (inertia) against different k values</em>) to ascertain the ideal number of clusters, visualized through an inertia plot. With the chosen number of clusters (k=4) we execute it, and project the high-dimensional data into two principal components using PCA for intuitive visualization.</p>
<p>The results of the patient segmentation shed light on how clustering can help us categorize patient into distinct groups based on their health profiles. This segmentation aids in personalizing treatment strategies, improving healthcare resource allocation, and identifying patterns within the patient population. Let's dive into key findings:</p>
<p>The plot of inertia versus the number of clusters, as shown in the figure above, depicts a clear elbow at around k=4, indicating that four clusters is the ideal number to segment the patients.</p>
<p>In the figure below, there is a visual representation of the four distinct clusters derived from our analysis. Each color represents a different cluster, and the two principal components (PC1 and PC2) are used to reduce the data's dimensions for easier visualization.</p>
<p>The scatterplot reveals clear separation among the clusters, with some overlap between clusters 1, 2 and 3, suggesting shared characteristics among these groups, while cluster 0 stands distinctly apart. This visualziation provides a high-level understanding of how the clusters are organized and the relationships between the patient groups.</p>
<p>These clusters uncovered distinct patient profiles that align with specific health and demographic characteristics, next is a breakdown of them:<br /><br /></p>
<p>&nbsp; &nbsp; - Cluster 0, 144 patients: youngest group with an average age of 20.81, least likely to have children with an average of 0.34, highest number of major surgeries at 1.13 average and no presence of cancer history.<br />&nbsp; &nbsp; Smallest group but their profile stands out due to their high surgery rate despite their young age. They may benefit from additional monitoring or pre-surgery interventions to improve outcomes</p>
<p><br />&nbsp; &nbsp; - Cluster 1, 805 patients: oldest group with an average age of 54.11, moderate presence of children with an average of 0.65, relatively low surgeries at 0.90 on average, cancer history is presence but low, at 2.36%.<br />&nbsp; &nbsp; Second largest group, representing an older demographic but with stable health. Might need targeted chronic care management ato prevent further complications.</p>
<p>&nbsp; &nbsp; - Cluster 2, 372 patients: middle-aged group, with an average age of 36.62, higher than average children at 0.97 and average surgery rate at 1.0 per person. 100% of patients have a cancer history.<br />&nbsp; &nbsp; Small cluster, all of whom have a cancer history, which can be prioritized for ongoing treatment and care coordination.</p>
<p>&nbsp; &nbsp; - Cluster 3, 1008 patients: average age similar to the cluster above, at 34.49. Highest children average at 1.44 and fewest surgeries, at 0.32 per patient. No significant presence of cancer or smokers in this group.<br />&nbsp; &nbsp; Largest group, reflecting a more typical, low-complication patient group, requiring fewer medical interventions. This group can be managed with preventive strategies to keep their health stable and reduce the likelihood of future complications.</p>
<p><strong>4. Predictive Modeling: forecasting charges and assessing risks</strong></p>
<p>The <em>predictionmodeling.py&nbsp;</em>script takes a deep dive into predictive analytics, focusing on two primary objectives: 1) predicting hospitalization charges, and 2) creating risk scores for patient complications.</p>
<p>Both tasks are essential in modern healthcare systems, as they help optimize financial planning and identifying hih-risk patients to deliver targeted, personalized care.</p>
<p>Accurate forecasting of hospitalization charges is crucial for effective financial management and planning, it enables hospitals and healthcare providers to anticipate costs and optimize resource allocation, ensuring efficing healthcare delivery.</p>
<p>The data was extracted from the hospitalization_details and medical_examination tables, combining a rich set of features including patient demographics, health metrics and hospitalization details. Then the features were selected (same as previously) and a Gradient Boosting Regressor was utilized due to its ability to handle complex interactions between features. It is particularly suited for capturing non-linear relationships in healthcare costs. A grid search was conducted with cross-validation to fine-tune hyperparameters such as learning rate, max depth and the number of estimators.</p>
<p>For evaluation, the model's performance was evaluated using the Mean Squared Error (MSE) and&nbsp;R&sup2; score to measure its predictive accuracy. Feature importance were visualized to understand which factors had the most significant impact on hospitalization charges.</p>
<p>The best hyperparameters identified by the grid search were the following ones:<br />&nbsp; &nbsp; - learning rate, 0.05<br />&nbsp; &nbsp; - max_depth, 3<br />&nbsp; &nbsp; - min_samples_leaf, 4<br />&nbsp; &nbsp; - min_samples_split, 10<br />&nbsp; &nbsp; - n_estimators, 100</p>
<p>The model's SME was 77,051,054.69 which indicates the average squared difference between predicted and actual charges.</p>
<p>The model achieved an R&sup2; score of 0.43, meaning that 43% of the variance in hospitalization charges can be explained by the model. While the score reflects a reasonable predictive capacity, it also suggests there are additional factors influencing charges that were not captured currently.</p>
<p>The top 3 most influential features driving hospitalization charges were: 1) hospital tier (57%), 2) BMI (22%) and 3) age (18%).</p>
<p>Now, for the risk scores for patient complications. Identifying patients at high risk of developing complications is critical for proactive healthcare management. By predicting which patients are more likely to experience severe health issues, healthcare provides can prioritie interventions, reduce complications, and potentially lower overall costs.</p>
<p>Complications, for the model, were defined primarly by the presence of heart issues or any transplants, as these conditions typically indicate a higher likelihood of severe health outcomes. Gradient Boosting Classifier was used to predict the likelihood of complications, with Grid Search for cross-validation to optimize hyperparameters.</p>
<p>The model was this time evaluated using a classification report that measured key metrics such as precision, recall and F-1 score. The ROC AUC score was also calculated to measure the model's ability to discriminate between high-risk and low-risk patients, which were classified into: low risk, moderate risk and high risk.</p>
<p>Optimal hyperparameters for the classifier were:<br />&nbsp; &nbsp; - learning rate, 0.1<br />&nbsp; &nbsp; - max_depth, 7<br />&nbsp; &nbsp; - min_samples_leaf, 4<br />&nbsp; &nbsp; - min_samples_split, 10<br />&nbsp; &nbsp; - n_estimators, 100</p>
<p>The model performed exceptionally well, achieving high precision and recall for both risk groups, with an overally accuracy of 97%.</p>
<p>The ability to predict hospitalization costs and assess patient risk based on complications offers powerful tools for both operational efficiency and patient care. These insights can inform financial planning, resource allocation, and help healthcare providers deliver more personalized care to patients, ultimately improving outcomes and reducing costs.</p>
<p><strong>5. Geospatial Analysis: mapping healthcare metrics across&nbsp;</strong><strong>states</strong></p>
<p>The geospatial analysis reveals regional disparities in healthcare charges and patient health metrics. Such insights are instrumental in identifying areas that require targeted interventions, optimizing resource distribution, and formulating region-specific healthcare policies.</p>
<p><strong>6. Cost Analysis: unveiling financial insights</strong></p>
<p>Effective cost management is crucial for the sustainability of healthcare institutions. The <em>costanalysis.py&nbsp;</em>script conducts an in-depth analysis of hospitalization charges, exploring their distribution, influencing factors, and interrelationships with other health metrics.</p>
<p>Data was loaded from cost_analysis_view, a dataset that includes patient demographics health metrics, and hospitalization charges.</p>
<p>With just a quick EDA (Exploratory Data Analysis) we can gather a lot of information already:&nbsp;</p>
<p>&nbsp; &nbsp; 1) Distribution of Charges: as visualized in the histogram, the distribution of hospitalization charges is righ-skewed,&nbsp;with most patients incurring charges below $20,000, while a few cases exceed $50,000. This skew suggests that while most hospitalizations remain moderately priced, outliers drive up the average.<br />&nbsp; &nbsp; 2) Charges vs. Age:&nbsp;a scatterplot shows a general upward trend in hospitalization charges as patient age increases. Although the relationship between age and charges is not strictly linear, older patients tend to face higher costs, potentially due to the complexity of care required.<br /><strong>&nbsp; &nbsp; </strong>3)&nbsp;Charges by Hospital Tier: a boxplot&nbsp; reveals significant differences in charges across hospital tiers. Tier 1 hospitals, often the most advanced or specialized, show the highest median charges, with a wider range of costs compared to Tier 2 and Tier 3 hospitals. This suggests that hospital tier is a key determinant of the financial burden.<br />&nbsp; &nbsp; 4) Correlation Matrix:&nbsp;a heatmap visualizes the correlations between key variables. Charges are strongly negatively correlated with hospital_tier, meaning that higher-tier hospitals (with lower numerical values for tier) are associated with higher costs.</p>
<p>This cost analysis provides actionable insights for healthcare administrators to refine budgeting and resource allocation strategies. By focusing on high-cost areas, such as patients with elevated BMI or older age groups, healthcare providers can design interventions that reduce costs while maintaining quality care.</p>
<p>The Ordinary Least Squares (OLS) regression was employed to quantify the impact of various factors on hospitalization charges. The OLS regression model achieved an&nbsp;Adjusted R-squared of 0.411, indicating that the model explains about 41.1% of the variability in hospitalization charges. Although there is room for improvement, this provides valuable insights into key cost drivers.</p>
<p>Significant predictors as age (older patients, higher costs, about $310 per year of age), also having more children correlates with a slight increase in charges, hospital tier, as expected, where higher tier hospitals are associated with significantly higher charges. Also higher BMI is a significant predictor, with an average of $380 increase per unit increase in BMI.</p>
<p>The VIF calculations reveal no severe multicollinearity among the predictors, as all VIF values were below 5, except for the constant. This suggests the model is stable and that the predictors are not highly redundant.</p>
<p>This cost analysis provides actionable insights for healthcare administrators to refine budgeting and resource allocation strategies. By focusing on high-cost areas, such as patients with elevated BMI or older age groups, healthcare providers can design interventions that reduce costs while maintaining quality care.</p>
<p><strong>7. Chronic Disease Management: predicting complications</strong></p>
<p>Managing chronic diseases effectively is critical for improving patient outcomes while reducing healthcare costs. The&nbsp;<em>chronicdisease.py</em>&nbsp;script leverages machine learning techniques to predict complications in patients with chronic conditions, stratifying risk levels based on various health factors.</p>
<p>Categorical variables were one-hot encoded where necessary, ensuring that the machine learning algorithms could appropriately interpret the data.</p>
<p>The&nbsp;GradientBoostingClassifier&nbsp;was chosen for its strong ability to handle imbalanced datasets and provide high predictive accuracy. The classifier was wrapped in a pipeline to streamline preprocessing, scaling numerical features, and encoding categorical ones.</p>
<p>A&nbsp;Grid Search&nbsp;with cross-validation was conducted to fine-tune the hyperparameters, optimizing the classifier&rsquo;s performance.</p>
<p>The classifier was evaluated using key metrics such as&nbsp;Precision,&nbsp;Recall,&nbsp;F1-Score, and<strong>&nbsp;</strong>ROC AUC, which provide a comprehensive view of the model&rsquo;s discriminative ability. The model yielded promising results, with a high&nbsp;ROC AUC score&nbsp;of 0.85, indicating excellent predictive power.</p>
<p>The&nbsp;Top 10 Features&nbsp;driving the prediction of complications were identified.&nbsp;HBA1C&nbsp;and the&nbsp;Number of Major Surgeries&nbsp;were the most significant predictors, followed closely by&nbsp;charges,&nbsp;BMI, and&nbsp;children. This underscores the importance of monitoring glucose control (as measured by HBA1C) and surgical history when assessing complication risks in chronic disease patients.</p>
<p>The trained model and its corresponding preprocessing pipeline were saved using&nbsp;<em>joblib</em>, enabling future deployment for real-time predictions. This model can now be utilized by healthcare providers to assess complication risks in chronic disease patients, offering tailored interventions to high-risk groups.</p>
<p><strong>8. Dashboard development: real-time monitoring with Streamlit</strong></p>
<p>To facilitate real-time monitoring and interactive exploration of healthcare data, an intuitive dashboard was developed using Streamlit. The <em>app.py</em> script orchestrates various data visualizations and functionalities, providing stakeholders with a comprehensive overview of patient metrics, facility utilization, and financial insights.</p>
<p>The dashboard serves as a centralized hub for monitoring healthcare operations, enabling data-driven decision-making. Its interactive nature allows users to drill down into specific metrics, fostering a deeper understanding of underlying patterns and trends.</p>
<p><strong>9. Scripts: structuring and querying the data</strong></p>
<p>Scripts can be found at ...</p>
<p><strong>10. Conclusion</strong></p>
<p>This project exemplifies the transformative potential of data analytics in healthcare. By integrating robust data preparation, advanced machine learning techniques, and interactive visualization tools, it provides a comprehensive framework for understanding and improving patient care, optimizing financial operations, and strategically planning healthcare services. As healthcare continues to evolve, such data-driven approaches will be instrumental in fostering a more efficient, responsive, and patient-centric healthcare system.</p>
  `
};