export default {
    id: "project-5",
    title: "Deep Marketing Data Analysis",
    image: "https://placehold.co/400x300",
    description: "Description of your second data project. Highlight the impact and results.",
    technologies: ["Python", "Marketing", "Data Analysis"],
    date: "2024-02-01",
    content: `
<p>&nbsp; &nbsp;&nbsp;1. The Basics<br />&nbsp; &nbsp;&nbsp;2. Client Behavior Analysis<br />&nbsp; &nbsp; 3. Stratified Sampling<br />&nbsp; &nbsp; 4. ROC Curve<br />&nbsp; &nbsp; 5. Conclusion and Recommendations</p>
<p><strong>1. The Basics</strong></p>
<p>Let&rsquo;s begin by explaining what marketing is. Paraphrasing the marketing genius Dr. Philip Kotler, marketing is defined as &ldquo;the science and art of exploring, creating, and delivering value to satisfy the needs of a target market at a profit. Marketing identifies unfulfilled needs and desires. It defines, measures, and quantifies the size of the identified market and the profit potential.&rdquo;</p>
<p>Marketing campaigns, on the other hand, consist of a set of actions and efforts aimed at reaching customers and achieving specific objectives. They are useful for achieving goals such as launching a product, increasing sales volume, enhancing brand exposure, and more.</p>
<p>For this project, we will use a dataset from the&nbsp;<a href="https://archive.ics.uci.edu/dataset/222/bank+marketing">UCI Machine Learning Repository</a>.</p>
<p>Before diving in, let&rsquo;s briefly define what a &ldquo;term deposit&rdquo; is. A term deposit is &ldquo;a fixed-term investment that includes the deposit of money into an account at a financial institution. Term deposit investments usually carry short-term maturities ranging from one month to a few years and will have varying levels of required minimum deposits.&rdquo; (defined by Investopedia.com)</p>
<p>Let&rsquo;s start by exploring the basics.</p>
<p>With just a few lines of code, we can start working with the data and begin to understand it. In this particular dataset, the bulk of the information is not derived from numerical columns but from categorical ones.</p>
<p>&nbsp; &nbsp; - The minimum age is 18 years, with a maximum recorded age of 95. The average age is 41 years.<br />&nbsp; &nbsp; - The&nbsp;average account balance is $1,528. However, the high standard deviation indicates significant variability in individual balances across the dataset. This wide range suggests that many accounts deviate considerably from the average, with some balances being much higher or lower than the mean.<br />&nbsp; &nbsp; - Upon&nbsp;careful examination, it is evident that removing the duration column from our predictive model would be beneficial. This recommendation is based on the nature and timing of the duration variable in relation to client interactions. Specifically, duration data is only available after contact has been made with a potential client, making it unsuitable for predictive purposes when approaching new prospects who have not yet been contacted.</p>
<p>Fortunately, in this dataset, there are no missing values. Depending on the specific needs of the project, missing data could be handled in various ways&mdash;such as removing the rows with missing values, imputing missing values with the mean, or attempting to retrieve the data manually from other sources.</p>
<p>If we continue with our analysis:</p>
<p>&nbsp; &nbsp; - Number&nbsp;&nbsp;of Occupations: Management is the occupation that is more prevalent in this dataset.<br />&nbsp; &nbsp; - Age&nbsp;by Occupation: As expected, the retired are the ones who have the highest median age while student are the lowest.<br />&nbsp; &nbsp; - Balance&nbsp;by Occupation: Management and Retirees are the ones who have the highest balance in their accounts.</p>
<p><strong>2. Client Behavior Analysis</strong></p>
<p></p>
<p>An analysis of the campaign duration data reveals significant insights into client behavior and term deposit acquisition patterns. The data demonstrates a strong positive correlation between the duration of client interactions and the likelihood of term deposit openings. This relationship suggests that extended engagement with clients is a key factor in successful conversions.</p>
<p>The average campaign duration across all interactions stands at 374.76 units. This benchmark provides a useful threshold for segmenting client interactions and analyzing their outcomes. When examining the data through this lens, a clear pattern emerges: clients whose interactions exceeded the average duration showed a markedly higher propensity to open term deposits.</p>
<p>Specifically, within the cohort of clients whose interaction durations surpassed the mean, 78% proceeded to open term deposit accounts. In contrast, among those with below-average interaction durations, only 32% opted for term deposits. This substantial disparity in conversion rates underscores the critical role of prolonged engagement in fostering client trust and commitment.</p>
<p>Given these findings, it would be strategically advantageous to prioritize and cultivate longer interactions with potential clients. Focusing resources on individuals who demonstrate a willingness to engage in extended conversations could significantly enhance the efficiency and effectiveness of our term deposit acquisition efforts. This targeted approach aligns with the data-driven insights and promises to optimize our campaign outcomes.</p>
<p><strong>3. Stratified Sampling</strong></p>
<p>Stratified sampling is a crucial yet often overlooked technique in model development, applicable to both regression and classification tasks. This method ensures that key features influencing the target variable are proportionally represented in both training and test datasets, thereby enhancing model reliability and generalizability.<br /><br />To illustrate the importance of stratified sampling, let&rsquo;s consider the feature of personal loans in our term deposit prediction model. This variable significantly impacts the likelihood of a client opening a term deposit, as evidenced by its -11% correlation with the target variable in our correlation matrix.<br /><br />Before implementing stratified sampling, a thorough analysis of the data distribution is essential. In this case, we&rsquo;ve observed that the &lsquo;loan&rsquo; column shows a distinct imbalance: 87% of clients do not have personal loans, while 13% do. To maintain the integrity of our model and prevent bias, it&rsquo;s crucial that both our training and test sets mirror this distribution.<br /><br />The process of implementing stratified sampling in this context involves three key steps:</p>
<p>&nbsp; &nbsp; 1) Analyze&nbsp;the distribution of the influential feature (personal loans) in the entire dataset.<br />&nbsp; &nbsp; 2) Identify&nbsp;the proportions of each category within this feature (87% without loans, 13% with loans).<br />&nbsp; &nbsp; 3) Ensure&nbsp;that these proportions are maintained when splitting the data into training and test sets.</p>
<p>By adhering to this stratified sampling approach, we safeguard against overfitting and ensure that our model&rsquo;s performance on the test set is a true reflection of its real-world applicability. This method is particularly valuable when dealing with imbalanced datasets or when certain features have a disproportionate impact on the target variable.<br /><br />Ultimately, stratified sampling contributes to the development of more robust and reliable predictive models, capable of performing consistently across various subsets of the data.</p>
<p>Now we have to avoid overfitting.</p>
<p>Overfitting occurs when a modeling algorithm captures random noise in the data rather than identifying the underlying pattern. This issue becomes evident when a model performs exceptionally well on the training data but fails to generalize effectively to the test data, resulting in poor performance on new, unseen data. Essentially, overfitting means the model has memorized the training data rather than learning to generalize from it. For instance, if a Decision Tree Classifier or Random Forest Classifier shows near-perfect accuracy scores (e.g., 100% or 99%) on the training data but performs poorly on test data, it is likely overfitting.</p>
<p>To mitigate overfitting, cross-validation is a highly effective technique. This involves dividing the dataset into multiple subsets. For example, with a 3-fold cross-validation, the data is split into three parts: two-thirds (66%) is used for training and one-third (33%) for testing. This process is repeated three times, ensuring that each subset is used for both training and testing. Cross-validation helps capture the overall pattern of the data and ensures that the model generalizes well across different subsets of the dataset.</p>
<p>Once trained, a confusion matrix helps assess the model's classification performance, such as predicting client term deposit subscriptions. It breaks down predictions into True Positives, False Positives, True Negatives, and False Negatives.</p>
<p>&nbsp; &nbsp; - True&nbsp;Negatives (Top-Left Cell):&nbsp;The count of instances where the model correctly predicted that clients would not subscribe to a term deposit.<br />&nbsp; &nbsp; - False&nbsp;Negatives (Top-Right Cell):&nbsp;The count of instances where the model incorrectly predicted that clients would not subscribe, even though they did.<br />&nbsp; &nbsp; - False Positives&nbsp;(Bottom-Left Cell):&nbsp;The count of instances where the model incorrectly predicted that clients would subscribe, even though they did not.<br />&nbsp; &nbsp; - True&nbsp;Positives (Bottom-Right Cell):&nbsp;The count of instances where the model correctly predicted that clients would subscribe to a term deposit.</p>
<p>The confusion matrix provides insight into the model's performance by showing accurate and inaccurate predictions across categories, achieving a Gradient Boost Classifier accuracy of 0.85. To better understand these results, we can examine two key metrics: Recall and Precision. Recall measures the model's ability to identify all relevant instances (true positive rate), while Precision indicates the accuracy of positive predictions. These metrics have an inherent tradeoff - increasing precision often decreases recall, as seen when raising precision thresholds makes the model more conservative in positive predictions. Our precision score is&nbsp;0.8244135732179458, and our recall score is&nbsp;0.8553875236294896.</p>
<p><strong>4. ROC Curve (Receiver Operating Characteristic)</strong></p>
<p>The ROC curve is a graphical representation used to evaluate the performance of a classification model. It illustrates the model&rsquo;s ability to distinguish between two classes, such as term deposit subscriptions (True Positives) versus non-subscriptions.</p>
<p>As the classification threshold changes, the ROC curve plots various combinations of the false positive rate and true positive rate. A model that performs well will have its ROC curve close to the top-left corner of the plot, indicating high true positive rates and low false positive rates. The area under the ROC curve (AUC) is often used as a summary measure of the model&rsquo;s performance, with a value closer to 1 indicating better overall classification ability.</p>
<p>&nbsp; &nbsp; - Gradient Boost Classifier Score:&nbsp;0.9173128596743366<br />&nbsp; &nbsp; - Neural Classifier Score:&nbsp;0.9167698643666292<br />&nbsp; &nbsp; - Naives Bayes Classifier Score:&nbsp;0.803363959942255</p>
<p>Now we need to know the features influencing term deposit subscription results, and for that we use a decision tree classifier, as it identifies several key features that significantly impact the likelihood of a term deposit subscription:</p>
<p>&nbsp; &nbsp; 1) Duration:&nbsp;the length of the conversation between the sales representative and the potential client. Longer conversations are often associated with higher subscription rates.<br />&nbsp; &nbsp; 2) Contact:&nbsp;the number of contacts made to the potential client within the same marketing campaign. More contacts generally increase the likelihood of a subscription.<br />&nbsp; &nbsp; 3) Month:&nbsp;the month of the year when the contact was made. Seasonal variations can influence client behavior and subscription rates.</p>
<p>These features are considered the most influential in predicting whether a potential client will subscribe to a term deposit.</p>
<p><strong>5. Conclusion and Recommendations</strong></p>
<p>1) Months&nbsp;of Marketing Activity:&nbsp;the highest level of marketing activity occurred in May, but this month also had the lowest effective subscription rate (-34.49%). For future campaigns, it would be beneficial to concentrate efforts in March, September, October, and December. December&rsquo;s low marketing activity might be an opportunity for increased engagement, warranting further investigation.</p>
<p>2) Seasonality:&nbsp;potential clients show a higher tendency to subscribe to term deposits during the fall and winter seasons. Future marketing campaigns should align with these seasons to enhance effectiveness.</p>
<p>3) Campaign&nbsp;Calls: implement a policy to limit contact to no more than three calls per potential client. Excessive calls increase the likelihood of rejection. Streamlining contact strategies can improve overall campaign efficiency.</p>
<p>4) Age Category: focus the marketing campaign on individuals in their 20s or younger and those aged 60 and older. The youngest age group has a 60% subscription rate, while the eldest category shows a 76% subscription rate. Targeting these demographics could boost subscription rates.</p>
<p>5) Occupation: target potential clients who are students or retired individuals. Retired clients are inclined to invest in term deposits to earn interest on their savings, while students also show a tendency to subscribe. Tailoring the campaign to these occupations may increase success.</p>
<p>6) House Loands and Balances: potential clients with lower balances are more likely to have house loans, which limits their capacity to subscribe to term deposits. Conversely, individuals with average or high balances are less likely to have house loans and more likely to open term deposits. Future campaigns should focus on clients with average and high balances.</p>
<p>7) Develop a Questionnaire for Calls: since call duration correlates positively with subscription likelihood, incorporating an engaging questionnaire could extend conversation length. While this does not guarantee a subscription, it can increase client engagement and potentially improve conversion rates.</p>
<p>8) Target Individuals with Higher Duration (Above 375 seconds): focus on potential clients whose call duration exceeds 375 seconds. This group shows a high likelihood (78%) of opening a term deposit account, suggesting that targeting them could significantly improve campaign success rates.</p>
    `
  };